// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from 'three';
// import React from 'react';
// import { useGLTF } from '@react-three/drei/native';
// import { GLTF } from 'three-stdlib';

// type GLTFResult = GLTF & {
//     nodes: {
//         Object_4: THREE.Mesh;
//     };
//     materials: {
//         'Material.001': THREE.MeshStandardMaterial;
//     };
// };

// export default function Model(props) {
//     const { nodes, materials } = useGLTF(require('../assets/model/earths.glb')) as GLTFResult;
//     return (
//         <group {...props} dispose={null}>
//             <mesh
//                 castShadow
//                 receiveShadow
//                 geometry={nodes.Object_4.geometry}
//                 material={materials['Material.001']}
//                 rotation={[Math.PI / 2, 0, 0]}
//             />
//         </group>
//     )
// }

// useGLTF.preload(require('../assets/model/earths.glb'))
